### ISSUE TITLE
Review User Story in the Wiki

### ISSUE THREAD

**Issue by parkj6** [cs361-W16/Group17-2#16]
**Card**: As a User, I want to be able to choose which deck to play with, so that I feel the game is worth paying for.

**Conversation**:
-The user should have the chance to choose which deck they want to play with at the beginning of the game.
-The US deck option should have the deck as currently exists
-The Spanish deck option should support a standard Spanish Deck
    The deck consists of 40 cards, divided into 4 suits: Coins, Cups, Swords and Clubs.
    Each Suit consists of 1-7, Jack, Knight, and King. The "Ace" is 1, and is low.
-The game logic (such as remove and move) should work for both decks.

**Confirmation**: This is to be filled in by your group.

**Comment by edwardrh** [comment]
I created a new page on our Wiki stating this User Story, but the user story still needs the confirmation section to be filled/revised.

**Comment by parkj6** [comment]
added.
